version: '3'
services:
  db:
    container_name: postgres
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/myapp/backend
    depends_on:
      - db
    ports:
      - "3000:3000"
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: "node:14-alpine"
    user: "node"
    working_dir: /myapp/frontend
    volumes:
      - ./frontend:/myapp/frontend
    command: "yarn start"
    ports:
      - "9999:9999"
    depends_on:
      - backend
